import type { Metadata } from "next";
import "./globals.css";
import Header from "./compornents/Header";
import Footer from "./compornents/Footer";
import { Suspense } from "react";
import Loading from "./loding";
import Favicon from "../../public/favicons/favicon.png";
import ScrollTopButton from "./compornents/ScrollTopButton";

export const metadata: Metadata = {
  title: "ポートフォリオ",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <div>
          <Header />
          <Suspense fallback={<Loading />}>
            {children}
            <ScrollTopButton />
          </Suspense>
          <Footer />
        </div>
      </body>
    </html>
  );
}
